# Generated by Django 6.0 on 2026-03-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(10, 'Easy (+10 XP)'), (30, 'Medium (+30 XP)'), (50, 'Hard (+50 XP)'), (100, 'Epic (+100 XP)')], default=10),
        ),
    ]
