# Generated by Django 6.0 on 2026-03-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_deadline_extensions_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='coins_earned',
            field=models.IntegerField(default=0),
        ),
    ]
